CREATE TABLE "GCG_6765_DAILY" (
 "TERMINAL_NO" CHAR(3),
 "REPORT_ID" CHAR(6),
 "PRIMARY_GRP" CHAR(2),
 "BACKLOG" NUMERIC(16,4),
 "DAILY_BOOKING" NUMERIC(16,4),
 "MTD_BOOKING" NUMERIC(16,4),
 "YTD_BOOKING" NUMERIC(16,4),
 "DAILY_INVOICING" NUMERIC(16,4),
 "MTD_INVOICING" NUMERIC(16,4),
 "YTD_INVOICING" NUMERIC(16,4) );
